---
resources:
- name: nodejs-code
  type: git
  icon: github
  source:
    uri: https://github.com/shehuawwal/nodejs-webapp
    branch: master

- name: build-nodejs-webapp
  type: registry-image
  icon: docker
  source:
    repository: docker.io
    tag: latest
    username: ((docker_username))
    password: ((docker_password))

jobs:
- name: nodejs-webapp-test
  plan:
  - get: nodejs-code
    trigger: true
  - task: build-nodejs-webapp
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}

      inputs:
      - name: nodejs-code

      outputs:
      - name: nodejs-webapp
      run:
          path: sh
          args:
          - -exec
          - |
            ls
            apt update && apt install docker.io -y
            systemctl start docker
            docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD
            docker build -t nodejs-webapp:latest .
            docker images
            # docker push shehuawwal/nodejs-webapp:latest
